name: test

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: "perl:5.32"
    steps:
      - uses: actions/checkout@v2
      - name: Install Toolchain
        run: cpanm -q -n --no-man-pages App::cpm
      - name: Install Toolchain
        run: cpm install -g Dist::Zilla
      - name: Install Authoring Dependencies
        run: dzil authordeps --missing | cpm install -g -
      - name: Install Module Dependencies
        run: dzil listdeps --missing | cpm install -g -
      - name: smoke
        run: dzil smoke
